export const ADMIN_LOGIN_FAILURE='ADMIN_LOGIN_FAILURE'
export const ADMIN_LOGIN_REQUEST='ADMIN_LOGIN_REQUEST'
export const ADMIN_LOGIN_SUCCESS='ADMIN_LOGIN_SUCCESS'

export const GET_ADMIN_SUCCESS = 'GET_ADMIN_SUCCESS'
export const GET_ADMIN_FAILURE = 'GET_ADMIN_FAILURE'
export const GET_ADMIN_REQUEST = 'GET_ADMIN_REQUEST'

export const ADMIN_LOGOUT='ADMIN_LOGOUT';