
export const MENTOR_REGISTER_REQUEST='MENTOR_REGISTER_REQUEST'
export const MENTOR_REGISTER_SUCCESS='MENTOR_REGISTER_SUCCESS'
export const MENTOR_REGISTER_FAILURE='MENTOR_REGISTER_FAILURE'

export const MENTOR_LOGIN_SUCCESS='MENTOR_LOGIN_SUCCESS'
export const MENTOR_LOGIN_FAILURE='MENTOR_LOGIN_FAILURE'
export const MENTOR_LOGIN_REQUEST='MENTOR_LOGIN_REQUEST'

export const GET_MENTOR_SUCCESS = 'GET_MENTOR_SUCCESS'
export const GET_MENTOR_FAILURE = 'GET_MENTOR_FAILURE'
export const GET_MENTOR_REQUEST = 'GET_MENTOR_REQUEST'

export const LOGOUT='LOGOUT';