export const QA_LOGIN_FAILURE='QA_LOGIN_FAILURE'
export const QA_LOGIN_REQUEST='QA_LOGIN_REQUEST'
export const QA_LOGIN_SUCCESS='QA_LOGIN_SUCCESS'

export const GET_QA_SUCCESS = 'GET_QA_SUCCESS'
export const GET_QA_FAILURE = 'GET_QA_FAILURE'
export const GET_QA_REQUEST = 'GET_QA_REQUEST'

export const QA_LOGOUT='QA_LOGOUT';